Order.destroy_all
Wallet.destroy_all
Bid.destroy_all
Auction.destroy_all
Product.destroy_all
User.destroy_all

admin1 = User.create!(username:"Abel", email:"locatiabelal@gmail.com", address:"Metz", password: "lewagon", admin: true)
admin2 = User.create!(username:"Alex", email:"alex@gmail.com", address:"Frankfurt", password: "lewagon", admin: true)
admin3 = User.create!(username:"Tony", email:"tony@gmail.com", address:"Glasgow", password: "lewagon", admin: true)
admin4 = User.create!(username:"Mitch", email:"mitch@gmail.com", address:"Paris", password: "lewagon", admin: true)

# admin1.wallet.update(balance_cents: 1000)
# admin2.wallet.update(balance_cents: 1000)
# admin3.wallet.update(balance_cents: 1000)
# admin4.wallet.update(balance_cents: 1000)

product1 = Product.create!(name:"IPhone X", recommended_retail_price_cents:  100000)
product2 = Product.create!(name: "Applewatch", recommended_retail_price_cents: 20000)
product3 = Product.create!(name:"Rolex", recommended_retail_price_cents: 500000)
product4 = Product.create!(name:"Almond Cakes", recommended_retail_price_cents: 100)

# user1 = User.create!(username:"ally", email:"ally@gmail.com", address:"Cap Town", password: "password")
# user2 = User.create!(username:"andreia", email:"andreia@gmail.com", address:"Lisbon", password: "password")
# user3 = User.create!(username:"antoine", email:"antoine@gmail.com", address:"Lille", password: "password")
# user4 = User.create!(username:"arthur", email:"arthur@gmail.com", address:"Luxembourg", password: "password")
# user5 = User.create!(username:"catarina", email:"catarina@gmail.com", address:"Acores", password: "password")
# user6 = User.create!(username:"david", email:"david@gmail.com", address:"Amsterdam", password: "password")
# user7 = User.create!(username:"diogo", email:"diogo@gmail.com", address:"Lisbon, but on the other side", password: "password")
# user8 = User.create!(username:"emily", email:"emily@gmail.com", address:"Dublin", password: "password")
# user9 = User.create!(username:"joana", email:"joana@gmail.com", address:"Bruxelles", password: "password")
# user10 = User.create!(username:"jerome", email:"jerome@gmail.com", address:"Bruxelles/Medellin", password: "password")
# user11 = User.create!(username:"laura", email:"laura@gmail.com", address:"San Francisco", password: "password")
# user12 = User.create!(username:"maria", email:"maria@gmail.com", address:"Lisbon", password: "password")
# user13 = User.create!(username:"marta", email:"marta@gmail.com", address:"Lisbon", password: "password")
# user14 = User.create!(username:"max", email:"max@gmail.com", address:"Frankfurt", password: "password")
# user15 = User.create!(username:"monica", email:"monica@gmail.com", address:"Lisbon", password: "password")
# user16 = User.create!(username:"pavel", email:"pavel@gmail.com", address:"Krasnodar", password: "password")
# user17 = User.create!(username:"pedro", email:"pedro@gmail.com", address:"Lisbon", password: "password")
# user18 = User.create!(username:"swen", email:"swen@gmail.com", address:"Somewhere in Germany", password: "password")
# user19 = User.create!(username:"todd", email:"todd@gmail.com", address:"Salt Lake City", password: "password")
# user20 = User.create!(username:"shannon", email:"shannon@gmail.com", address:"Texaaas", password: "password")
# user21 = User.create!(username:"rui", email:"rui@gmail.com", address:"Hong Kong", password: "password")

# user1.wallet.update(balance_cents: 100)
# user2.wallet.update(balance_cents: 100)
# user3.wallet.update(balance_cents: 100)
# user4.wallet.update(balance_cents: 100)
# user5.wallet.update(balance_cents: 100)
# user6.wallet.update(balance_cents: 100)
# user7.wallet.update(balance_cents: 100)
# user8.wallet.update(balance_cents: 100)
# user9.wallet.update(balance_cents: 100)
# user10.wallet.update(balance_cents: 100)
# user11.wallet.update(balance_cents: 100)
# user12.wallet.update(balance_cents: 100)
# user13.wallet.update(balance_cents: 100)
# user14.wallet.update(balance_cents: 100)
# user15.wallet.update(balance_cents: 100)
# user16.wallet.update(balance_cents: 100)
# user17.wallet.update(balance_cents: 100)
# user18.wallet.update(balance_cents: 100)
# user19.wallet.update(balance_cents: 100)
# user20.wallet.update(balance_cents: 100)
# user21.wallet.update(balance_cents: 100)

auction1 = Auction.create!(starting_time: DateTime.now - 1, ending_time: (DateTime.now + 2), fee_per_bid_cents: 25, price_step_cents: 10, status: 1, min_number_bids: 20, product: product1 )
auction2 = Auction.create!(starting_time: DateTime.now - rand(1..4), ending_time: DateTime.now + rand(1..4), fee_per_bid_cents: 10, price_step_cents: 10, status: 1, min_number_bids: 10, product: product2 )
auction3 = Auction.create!(starting_time: DateTime.now - rand(1..4), ending_time: DateTime.now + rand(1..4), fee_per_bid_cents: 100, price_step_cents: 100, status: 2, min_number_bids: 10, product: product3 )

# bid1 = Bid.create!(price_cents: 130, won: 0, auction: auction1, user: user1)
# bid2 = Bid.create!(price_cents: 200, won: 0, auction: auction1, user: user1)
# bid9 = Bid.create!(price_cents: 120, won: 0, auction: auction1, user: user1)

# bid6 = Bid.create!(price_cents: 100, won: 0, auction: auction1, user: user3)
# bid11 = Bid.create!(price_cents: 300, won: 0, auction: auction1, user: user3)
# bid4 = Bid.create!(price_cents: 100, won: 0, auction: auction2, user: user3)

# bid8 = Bid.create!(price_cents: 120, won: 0, auction: auction1, user: user2)
# bid10 = Bid.create!(price_cents: 300, won: 0, auction: auction1, user: user2)
# bid12 = Bid.create!(price_cents: 200, won: 0, auction: auction1, user: user2)
# bid3 = Bid.create!(price_cents: 100, won: 0, auction: auction1, user: user2)
# bid5 = Bid.create!(price_cents: 10, won: 0, auction: auction2, user: user2)
